# .github/workflows/print-message.yml

name: Print Hello Message

on:
  push:
    branches:
      - main

jobs:
  print-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: |
          echo "Hello, GitHub Actions!"
